### ISSUE TITLE
Problems generating an app

### ISSUE THREAD

**Issue by jconlon** [apollo-elements/apollo-elements#187]
Have problems creating an application with the generator:

```
$ npm init @apollo-elements -- app --uri /graphql --install --overwrite --package-defaults
TypeError: Cannot read property 'includes' of undefined
    at prompt (file:///home/jconlon/.npm/_npx/6047a8fb4d472788/node_modules/@apollo-elements/create/prompt.js:227:27)
    at async main (file:///home/jconlon/.npm/_npx/6047a8fb4d472788/node_modules/@apollo-elements/create/index.js:4:9)
```
Have tried it without the arguments but still have the problem

```
? What would you like to generate? Scaffold an app project
? What is the URI to your GraphQL endpoint? /graphql
TypeError: Cannot read property 'includes' of undefined
    at prompt (file:///home/jconlon/.npm/_npx/6047a8fb4d472788/node_modules/@apollo-elements/create/prompt.js:227:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///home/jconlon/.npm/_npx/6047a8fb4d472788/node_modules/@apollo-elements/create/index.js:4:9)
```

**Comment by bennypowers** [comment]
Thank you for the report. I wasn't able to reproduce. Have you used the generator in the past? If so, try clearing your npx cache with `rm -rf ~/.npm/_npx`, and please let me know if that solves it. See also https://github.com/npm/feedback/discussions/163

**Comment by jconlon** [comment]
Still having a problem after I `rm -rf ~/.npm/_npx`.
Took a look at [npm/feedback#163](https://github.com/npm/feedback/discussions/163) ...
Here is my error:

```
? What would you like to generate? Scaffold an app project
? What is the URI to your GraphQL endpoint? /graphql
TypeError: Cannot read property 'includes' of undefined
    at prompt (file:///home/jconlon/node_modules/@apollo-elements/create/prompt.js:227:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///home/jconlon/node_modules/@apollo-elements/create/index.js:4:9)
jconlon@mullet:~/experiments/WebComponents/apollo-gen-1$ npm info @apollo-elements/create version
3.0.1
jconlon@mullet:~/experiments/WebComponents/apollo-gen-1$ npm ls -g --depth=0
/home/jconlon/.nvm/versions/node/v16.8.0/lib
└── npm@7.21.1

jconlon@mullet:~/experiments/WebComponents/apollo-gen-1$ npm ls  --depth=0
jconlon@ /home/jconlon
├── @apollo-elements/create@3.0.1
└── @web/dev-server@0.1.22
```
Any ideas??

**Comment by bennypowers** [comment]
Can you change that line to read
```
    if (error?.command?.includes?.('build:codegen'))
```
then retry and post the error?

**Comment by jconlon** [comment]
Did so and now am getting:

```
$ npm init @apollo-elements -- app --uri /graphql --install --overwrite --package-defaults
Error: You must provide a `choices` parameter
    at CheckboxPrompt.throwParamError (/home/jconlon/node_modules/inquirer/lib/prompts/base.js:79:11)
    at new CheckboxPrompt (/home/jconlon/node_modules/inquirer/lib/prompts/checkbox.js:25:12)
    at PromptUI.fetchAnswer (/home/jconlon/node_modules/inquirer/lib/ui/prompt.js:100:25)
    at MergeMapSubscriber._tryNext (/home/jconlon/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/home/jconlon/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/jconlon/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/jconlon/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/home/jconlon/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/home/jconlon/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/jconlon/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)

```

**Comment by bennypowers** [comment]
Thank you for that.

The recent 3.0 release swapped `prompts` package for `inquirer`, which has a different error type. As well, I had used the `checkbox` input type for boolean options, when the `confirm` type was what I should have used. 

These should be fixed in 46c6439a3 and 5746761805e4f37715cab06d86796999c9658db7, respectively, and released in [v3.0.2](https://www.npmjs.com/package/@apollo-elements/create/v/3.0.2)

Please rimraf your cache and try again

**Comment by jconlon** [comment]
After rimraf cache I still had the v3.0.1 create, so I just installed v3.0.2 myself.  But when I did a:
`npm init @apollo-elements -- app --uri /graphql --install --overwrite --package-defaults`  It will generate the app framework but when it tries to start it fails with: 
```
> apollo-elements-app@1.0.0 start:serve
> wds --watch --open

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/jconlon/experiments/WebComponents/apollo/node_modules/@apollo-elements/create/helpers.js' imported from /home/jconlon/experiments/WebComponents/apollo/web-dev-server.config.mjs
Did you mean to import @apollo-elements/create/helpers.js?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:389:11)
    at moduleResolve (node:internal/modules/esm/resolve:867:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:978:11)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
ERROR: "start:serve" exited with 1.
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:internal/fs/promises:720:5)
    at app (file:///home/jconlon/node_modules/@apollo-elements/create/app.js:84:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async prompt (file:///home/jconlon/node_modules/@apollo-elements/create/prompt.js:193:20)
    at async main (file:///home/jconlon/node_modules/@apollo-elements/create/index.js:4:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}


```
Noticed the package.json had the old version of:

```
"devDependencies": {
    "@apollo-elements/create": "^2.x",
```
After modifying it to:
`"@apollo-elements/create": "^3.x",` and doing a `npm install` I was finally able to bring up the server.

**Comment by bennypowers** [comment]
indeed that dependency was out of date in the template.
3.0.3 updates those dependencies. These reports are very helpful, thank you again.

**Comment by jconlon** [comment]
Your welcome, thanks for the support.
