### ISSUE TITLE
Error on npm init @apollo-elements

### ISSUE THREAD

**Issue by christian-schoenefeld** [apollo-elements/apollo-elements#227]
## Package

`@apollo-elements`

## Description
When trying to run npm init @apollo-elements I get the following error:

```npx: Installierte 574 in 72.33s
/home/deploy/.npm/_npx/69152/lib/node_modules/@apollo-elements/create/bin/main.js:2
import { main } from '../index.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by christian-schoenefeld** [comment]
Sorry it was my mistake and was due to an outdated npm and node version

**Comment by bennypowers** [comment]
Thanks for the report, glad you got sorted
