### ISSUE TITLE
[bug] Include @apollo-elements/rollup-plugin-graphql package

### ISSUE THREAD

**Issue by heyMP** [apollo-elements/apollo-elements#230]
## Package
﻿
`@apollo-elements/create`

## Description

When running an `npm run build` I get an error that the following package is not included.

```bash
   npm run build

> apollo-elements-app@1.0.0 build
> run-s build:*


> apollo-elements-app@1.0.0 build:codegen
> graphql-codegen

(node:6372) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ Parse configuration
  ✔ Generate outputs

> apollo-elements-app@1.0.0 build:rollup
> rollup -c

[!] Error: Cannot find module '@apollo-elements/rollup-plugin-graphql'
Require stack:
- /Users/michael/Projects/apollo-elements-test/rollup.config.js
- /Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@apollo-elements/rollup-plugin-graphql'
Require stack:
- /Users/michael/Projects/apollo-elements-test/rollup.config.js
- /Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/michael/Projects/apollo-elements-test/rollup.config.js:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.require.extensions.<computed> [as .js] (/Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/shared/loadConfigFile.js:618:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

ERROR: "build:rollup" exited with 1.
```

## Steps To Reproduce
1. Generate new apollo-elements app `npm init @apollo-elements`
2. Answer yes to `App`
3. Answer yes to all options
4. Install dependencies
5. Then run `npm run build`

**Comment by bennypowers** [comment]
I think we aught to remove that dependency altogether, since the generator's New Opinion™ is to use codegen to write typed document node files in-place

**Comment by bennypowers** [comment]
Can you try again with latest?
