### ISSUE TITLE
[bug] esbuild `startService` error when running build

### ISSUE THREAD

**Issue by heyMP** [apollo-elements/apollo-elements#231]
## Package
﻿

I believe: `@apollo-elements/create`

## Description
After scaffolding the apollo-elements app using `@apollo-elements/create` and running a rollup build with `npm run build` I get an error that of the following:

```bash
   npm run build

> apollo-elements-app@1.0.0 build
> run-s build:*


> apollo-elements-app@1.0.0 build:codegen
> graphql-codegen

(node:7717) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ Parse configuration
  ✔ Generate outputs

> apollo-elements-app@1.0.0 build:rollup
> rollup -c


index.html → build...
[!] (plugin esbuild) TypeError: esbuild.startService is not a function
TypeError: esbuild.startService is not a function
    at Object.buildStart (/Users/michael/Projects/apollo-elements-test/node_modules/rollup-plugin-esbuild/dist/index.js:81:33)
    at /Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/shared/rollup.js:22795:37
    at async Promise.all (index 0)
    at rollupInternal (/Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/shared/rollup.js:23545:9)
    at build (/Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/bin/rollup:1530:20)
    at runRollup (/Users/michael/Projects/apollo-elements-test/node_modules/rollup/dist/bin/rollup:1675:21)

ERROR: "build:rollup" exited with 1.
```

## Steps To Reproduce
1. Generate new apollo-elements app npm init @apollo-elements
2. Answer yes to App
3. Answer yes to all options
4. Install dependencies
5. Then run npm run build

## Fix

Upgrading to rollup-plusing-esbuild `3.0.0` fixes this issue: https://github.com/egoist/rollup-plugin-esbuild/issues/209

**Comment by bennypowers** [comment]
Can you try again with latest?
